name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.docker_user }}
        DOCKER_PASSWORD: ${{ secrets.docker_password }}
      run: | # adding multiple independant lines of bash scripting
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "login done"
    
    - name: Build Docker Image
      run: |
        docker build -t sancara/docker-graphql:0.0.2 .
        
    - name: Push Docker Image
      run: |
        docker push sancara/docker-graphql:0.0.2
        
        
#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
